images:
    # Path to the input images
    path: "zip_files"

    # Image types to include
    types:
    - zip

database:
    # Path to store tags database
    path: "example_output/image_tags.db"


tagging:
    # Define the tagging question
    tag question: "Is it a prostate Image ?"

    # Define tags and shortcut key to tag
    # Note format is "tag": "key"
    tags:
        Prostate: 1
        Not Prostate: 2
        Bad Image: 3

    # Allow selection of multiple labels
    multi-select: False

    # Join string for multiple labels
    multi-separator: " + "

    # Show remarks field
    allow remarks: True

interface:
    # Max image size in pixels
    max_width: 150
    max_height: 150

server:

    # Host and port for the Flask server
    host: "127.0.0.1"
    port: "8080"

    # Turns Flask debug mode on or off
    debug mode: True
